{% set name = "xmlrunner" %}
{% set version = "1.7.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmlrunner-{{ version }}.tar.gz
  sha256: 5a6113d049eca7646111ee657266966e5bbfb0b5ceb2e83ee0772e16d7110f39

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - xmlrunner
  commands:
    - pip check

about:
  home: https://github.com/pycontribs/xmlrunner
  license: LGPL-3.0-only
  # LICENSE possibily can be omitted in the next release
  # https://github.com/pycontribs/xmlrunner/blob/master/MANIFEST.in#L2
  license_file: LICENSE
  summary: 'PyUnit-based test runner with JUnit like XML reporting.'
  description: |
    unittest-xml-reporting is a unittest test runner that can save test results
    to XML files that can be consumed by a wide range of tools, such as build
    systems, IDEs and continuous integration servers.
  doc_url: https://github.com/pycontribs/xmlrunner 
  dev_url: https://github.com/pycontribs/xmlrunner

extra:
  recipe-maintainers:
    - stolpeo
